[package]
name = "comrak-wasm"
version = "0.0.7"
authors = ["Jeremy Nguyen <hi@jeremy.ng>"]
edition = "2024"
description = "Comrak markdown parser compiled to WebAssembly"
readme = "README.md"
homepage = "https://www.npmjs.com/package/comrak-wasm"
repository = "https://github.com/jeremy-code/comrak-wasm"
license = "BSD-2-Clause"
keywords = ["commonmark", "markdown"]
# This Cargo.toml is only meant for building, do not publish to crates.io
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# In version 0.53.0, comrak introduced alternative syntect backends, making
# Oniguruma the default. Since oniguruma is not Wasm-compatible due to including
# stdlib.h in oniguruma/src/regexec.c:36, this means we have to compile without
# the default features.
#
# https://github.com/kivikakk/comrak/blob/c5a3b45ce94460e37c54408cd51d9b526e8cb4d8/Cargo.toml#L71
# https://github.com/kivikakk/comrak/pull/812
# https://github.com/trishume/syntect/#pure-rust-fancy-regex-mode-without-onig
comrak = { version = "0.54.0", default-features = false, features = [
    "bon",
    "cli",
    "syntect-fancy",
] }
js-sys = "0.3.104"
serde = { version = "1.0.229", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
tsify = { version = "0.5.8", features = ["js", "wasm-bindgen"] }
wasm-bindgen = "0.2.127"

[dev-dependencies]
wasm-bindgen-test = "0.3.77"

[package.metadata.wasm-pack.profile.release]
wasm-opt = [
    # Optimization options
    "-Oz",

    # Tool options
    "--enable-nontrapping-float-to-int",
    "--enable-simd",
    "--enable-bulk-memory-opt",
]

[profile.release]
opt-level = "z"
strip = true
lto = true
panic = "unwind"
codegen-units = 1

[profile.release.package."comrak-wasm"]
# https://github.com/cloudflare/workers-rs/issues/1014
strip = "debuginfo"
