name: CI

on:
    push:
        branches: ["main"]
    pull_request:
        types: [opened, synchronize]

permissions: {} # Each job defines its own permissions explicitly

jobs:
    build:
        name: Build
        permissions:
            contents: read # Access to check out code and install dependencies
        runs-on: ubuntu-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v7

            - name: Set up pnpm package manager
              uses: pnpm/setup@v2
              with:
                  cache: true

            - name: Install dependencies
              run: pnpm install

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: wasm32-unknown-unknown
                  components: rustfmt clippy

            - name: Add wasm32-unknown-unknown target to Rust toolchain
              run: rustup target add wasm32-unknown-unknown

            - name: Install wasm-pack
              run: cargo install wasm-pack

            - name: Lint code with Clippy
              run: pnpm run lint

            - name: Check code formatting with rustfmt, oxfmt
              run: pnpm run format:check

            - name: Build
              run: pnpm run dev
