name: Release

on:
    push:
        branches: ["main"]

permissions: {} # Each job defines its own permissions explicitly

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        permissions:
            id-token: write # This is required for requesting the JWT
            contents: write # Required to create release
            pull-requests: write # Required to create PR
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v7
              with:
                  # Fetch all history for all branches and tags so that changesets can
                  # compare against the correct base branch
                  fetch-depth: 0

            - name: Set up pnpm package manager
              uses: pnpm/setup@v2
              with:
                  cache: true

            - uses: cargo-bins/cargo-binstall@main
              with:
                  version: 1.21.1

            - name: Install dependencies
              run: pnpm install

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: wasm32-unknown-unknown
                  components: rustfmt clippy

            - name: Add wasm32-unknown-unknown target to Rust toolchain
              run: rustup target add wasm32-unknown-unknown

            - name: Install wasm-opt
              run: |
                  sudo apt-get update
                  sudo apt-get --assume-yes install binaryen

            - name: Install cargo-edit
              run: |
                  cargo binstall --no-confirm cargo-edit@0.13.13

            - name: Build
              run: pnpm run build

            - name: Create pull request for version bump and publish to npm
              uses: changesets/action@v1
              with:
                  publish: pnpm run ci:publish
                  # Has to be in its own script, otherwise, error "Too many
                  # arguments passed to changesets - we only accept the command
                  # name as an argument"
                  #
                  # https://github.com/frontity/frontity/issues/386
                  version: pnpm run ci:version
                  commit: "chore(release): version packages"
                  title: "chore(release): version packages"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
